// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZaOz0LH34bDH5_F2d7zM9qUj69Z7bDhk',
    appId: '1:962302756528:web:b5ea03c4ce62ab6e471d75',
    messagingSenderId: '962302756528',
    projectId: 'listify-9b774',
    authDomain: 'listify-9b774.firebaseapp.com',
    storageBucket: 'listify-9b774.appspot.com',
    measurementId: 'G-DE5SVV48VJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD92nEMx8T34ALE7PTXUErYn-PB43M570g',
    appId: '1:962302756528:android:d9d2eb7d4a75e6bb471d75',
    messagingSenderId: '962302756528',
    projectId: 'listify-9b774',
    storageBucket: 'listify-9b774.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf5TxPHjJ0Ep728mHOQsvPu5z9_8wkbZI',
    appId: '1:962302756528:ios:f2569e7ea2260d20471d75',
    messagingSenderId: '962302756528',
    projectId: 'listify-9b774',
    storageBucket: 'listify-9b774.appspot.com',
    iosBundleId: 'com.example.listify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf5TxPHjJ0Ep728mHOQsvPu5z9_8wkbZI',
    appId: '1:962302756528:ios:f2569e7ea2260d20471d75',
    messagingSenderId: '962302756528',
    projectId: 'listify-9b774',
    storageBucket: 'listify-9b774.appspot.com',
    iosBundleId: 'com.example.listify',
  );
}
